//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalapagoatsOGL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Vocab {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Vocab() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GalapagoatsOGL.Vocab", typeof(Vocab).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOAT OF WAR.
        /// </summary>
        internal static string Vocab_00 {
            get {
                return ResourceManager.GetString("Vocab_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOST HORN-SHOTS.
        /// </summary>
        internal static string Vocab_01 {
            get {
                return ResourceManager.GetString("Vocab_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOAT.
        /// </summary>
        internal static string Vocab_02 {
            get {
                return ResourceManager.GetString("Vocab_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUICIDE GOAT.
        /// </summary>
        internal static string Vocab_03 {
            get {
                return ResourceManager.GetString("Vocab_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOST SUICIDES.
        /// </summary>
        internal static string Vocab_04 {
            get {
                return ResourceManager.GetString("Vocab_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEATH.
        /// </summary>
        internal static string Vocab_05 {
            get {
                return ResourceManager.GetString("Vocab_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EASY TARGET.
        /// </summary>
        internal static string Vocab_06 {
            get {
                return ResourceManager.GetString("Vocab_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOST HORNED PLAYER.
        /// </summary>
        internal static string Vocab_07 {
            get {
                return ResourceManager.GetString("Vocab_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HORN.
        /// </summary>
        internal static string Vocab_08 {
            get {
                return ResourceManager.GetString("Vocab_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BORN TO DIE.
        /// </summary>
        internal static string Vocab_09 {
            get {
                return ResourceManager.GetString("Vocab_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUICKEST DEATH.
        /// </summary>
        internal static string Vocab_10 {
            get {
                return ResourceManager.GetString("Vocab_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MILLISECOND.
        /// </summary>
        internal static string Vocab_11 {
            get {
                return ResourceManager.GetString("Vocab_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARMAGOATTON.
        /// </summary>
        internal static string Vocab_12 {
            get {
                return ResourceManager.GetString("Vocab_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THROWING THE BIGGEST NUMBER OF OBJECTS.
        /// </summary>
        internal static string Vocab_13 {
            get {
                return ResourceManager.GetString("Vocab_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBJECT.
        /// </summary>
        internal static string Vocab_14 {
            get {
                return ResourceManager.GetString("Vocab_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GREEN HOOF.
        /// </summary>
        internal static string Vocab_15 {
            get {
                return ResourceManager.GetString("Vocab_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EATING THE BIGGEST AMOUNT OF GRASS.
        /// </summary>
        internal static string Vocab_16 {
            get {
                return ResourceManager.GetString("Vocab_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRASS BLOCK.
        /// </summary>
        internal static string Vocab_17 {
            get {
                return ResourceManager.GetString("Vocab_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUKETASTIC!.
        /// </summary>
        internal static string Vocab_18 {
            get {
                return ResourceManager.GetString("Vocab_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EATING THE MOST PUKE.
        /// </summary>
        internal static string Vocab_19 {
            get {
                return ResourceManager.GetString("Vocab_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUKE.
        /// </summary>
        internal static string Vocab_20 {
            get {
                return ResourceManager.GetString("Vocab_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U-GOAT.
        /// </summary>
        internal static string Vocab_21 {
            get {
                return ResourceManager.GetString("Vocab_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSING MOST OF THE TIME UNDERWATER.
        /// </summary>
        internal static string Vocab_22 {
            get {
                return ResourceManager.GetString("Vocab_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECOND.
        /// </summary>
        internal static string Vocab_23 {
            get {
                return ResourceManager.GetString("Vocab_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPRICORN ONE.
        /// </summary>
        internal static string Vocab_24 {
            get {
                return ResourceManager.GetString("Vocab_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSING MOST OF THE TIME OVER THE CLOUDS.
        /// </summary>
        internal static string Vocab_25 {
            get {
                return ResourceManager.GetString("Vocab_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECOND.
        /// </summary>
        internal static string Vocab_26 {
            get {
                return ResourceManager.GetString("Vocab_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOAT SUPERSTAR.
        /// </summary>
        internal static string Vocab_27 {
            get {
                return ResourceManager.GetString("Vocab_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOR BLEATING THE MOST.
        /// </summary>
        internal static string Vocab_28 {
            get {
                return ResourceManager.GetString("Vocab_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLEAT.
        /// </summary>
        internal static string Vocab_29 {
            get {
                return ResourceManager.GetString("Vocab_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAPPY GOAT.
        /// </summary>
        internal static string Vocab_30 {
            get {
                return ResourceManager.GetString("Vocab_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPENDING MORE TIME IN AIR.
        /// </summary>
        internal static string Vocab_31 {
            get {
                return ResourceManager.GetString("Vocab_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEC.
        /// </summary>
        internal static string Vocab_32 {
            get {
                return ResourceManager.GetString("Vocab_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHO WILL BE THE WINNER?.
        /// </summary>
        internal static string Vocab_33 {
            get {
                return ResourceManager.GetString("Vocab_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUT FIRST A FEW.
        /// </summary>
        internal static string Vocab_34 {
            get {
                return ResourceManager.GetString("Vocab_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPECIAL PRIZES.
        /// </summary>
        internal static string Vocab_35 {
            get {
                return ResourceManager.GetString("Vocab_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE PRIZE POOL IS .
        /// </summary>
        internal static string Vocab_36 {
            get {
                return ResourceManager.GetString("Vocab_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  G.
        /// </summary>
        internal static string Vocab_37 {
            get {
                return ResourceManager.GetString("Vocab_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRASS FOR .
        /// </summary>
        internal static string Vocab_38 {
            get {
                return ResourceManager.GetString("Vocab_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  NO CLEAR WINNER.
        /// </summary>
        internal static string Vocab_39 {
            get {
                return ResourceManager.GetString("Vocab_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONLY LOOSERS!.
        /// </summary>
        internal static string Vocab_40 {
            get {
                return ResourceManager.GetString("Vocab_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE WINNER IS .
        /// </summary>
        internal static string Vocab_41 {
            get {
                return ResourceManager.GetString("Vocab_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GALAPAGOATS.
        /// </summary>
        internal static string Vocab_42 {
            get {
                return ResourceManager.GetString("Vocab_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRIAL MODE.
        /// </summary>
        internal static string Vocab_43 {
            get {
                return ResourceManager.GetString("Vocab_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALT+F4 TO QUIT.
        /// </summary>
        internal static string Vocab_44 {
            get {
                return ResourceManager.GetString("Vocab_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESS ENTER.
        /// </summary>
        internal static string Vocab_45 {
            get {
                return ResourceManager.GetString("Vocab_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO JOIN.
        /// </summary>
        internal static string Vocab_46 {
            get {
                return ResourceManager.GetString("Vocab_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USELESS FIELD.
        /// </summary>
        internal static string Vocab_47 {
            get {
                return ResourceManager.GetString("Vocab_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RANDOM USELESS FIELD .
        /// </summary>
        internal static string Vocab_48 {
            get {
                return ResourceManager.GetString("Vocab_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESS SPACE TO BEGIN.
        /// </summary>
        internal static string Vocab_49 {
            get {
                return ResourceManager.GetString("Vocab_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESS E TO GO SINGLE.
        /// </summary>
        internal static string Vocab_50 {
            get {
                return ResourceManager.GetString("Vocab_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESS E TO GO DOUBLE.
        /// </summary>
        internal static string Vocab_51 {
            get {
                return ResourceManager.GetString("Vocab_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY IN.
        /// </summary>
        internal static string Vocab_52 {
            get {
                return ResourceManager.GetString("Vocab_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEC..
        /// </summary>
        internal static string Vocab_53 {
            get {
                return ResourceManager.GetString("Vocab_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAITING FOR.
        /// </summary>
        internal static string Vocab_54 {
            get {
                return ResourceManager.GetString("Vocab_54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTHER PLAYERS.
        /// </summary>
        internal static string Vocab_55 {
            get {
                return ResourceManager.GetString("Vocab_55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO CONFIRM.
        /// </summary>
        internal static string Vocab_56 {
            get {
                return ResourceManager.GetString("Vocab_56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNECT ANOTHER.
        /// </summary>
        internal static string Vocab_57 {
            get {
                return ResourceManager.GetString("Vocab_57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTROLLER TO JOIN.
        /// </summary>
        internal static string Vocab_58 {
            get {
                return ResourceManager.GetString("Vocab_58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESS START.
        /// </summary>
        internal static string Vocab_59 {
            get {
                return ResourceManager.GetString("Vocab_59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESS A TO BEGIN.
        /// </summary>
        internal static string Vocab_60 {
            get {
                return ResourceManager.GetString("Vocab_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESS Y TO GO SINGLE.
        /// </summary>
        internal static string Vocab_61 {
            get {
                return ResourceManager.GetString("Vocab_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESS Y TO GO DOUBLE.
        /// </summary>
        internal static string Vocab_62 {
            get {
                return ResourceManager.GetString("Vocab_62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY IN.
        /// </summary>
        internal static string Vocab_63 {
            get {
                return ResourceManager.GetString("Vocab_63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROGRAMMING :   FILIPPO FALLERI    AND   MATTEO NICOLOTTI.
        /// </summary>
        internal static string Vocab_64 {
            get {
                return ResourceManager.GetString("Vocab_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ART :   GABRIELE FRATUS   GIANLUCA ROSSI   DAVIDE CANGEMI.
        /// </summary>
        internal static string Vocab_65 {
            get {
                return ResourceManager.GetString("Vocab_65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME IDEA AND LEVEL DESIGN:   FRANCESCO FICARELLI.
        /// </summary>
        internal static string Vocab_66 {
            get {
                return ResourceManager.GetString("Vocab_66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUSIC AND SFX:   STEFANO CREMONA.
        /// </summary>
        internal static string Vocab_67 {
            get {
                return ResourceManager.GetString("Vocab_67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOVE.
        /// </summary>
        internal static string Vocab_68 {
            get {
                return ResourceManager.GetString("Vocab_68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM.
        /// </summary>
        internal static string Vocab_69 {
            get {
                return ResourceManager.GetString("Vocab_69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GORE.
        /// </summary>
        internal static string Vocab_70 {
            get {
                return ResourceManager.GetString("Vocab_70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWAP.
        /// </summary>
        internal static string Vocab_71 {
            get {
                return ResourceManager.GetString("Vocab_71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLEAT.
        /// </summary>
        internal static string Vocab_72 {
            get {
                return ResourceManager.GetString("Vocab_72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUMP.
        /// </summary>
        internal static string Vocab_73 {
            get {
                return ResourceManager.GetString("Vocab_73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WON.
        /// </summary>
        internal static string Vocab_74 {
            get {
                return ResourceManager.GetString("Vocab_74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE TEAM WINNER IS .
        /// </summary>
        internal static string Vocab_75 {
            get {
                return ResourceManager.GetString("Vocab_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GALAPAGOS.
        /// </summary>
        internal static string Vocab_76 {
            get {
                return ResourceManager.GetString("Vocab_76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFERNO.
        /// </summary>
        internal static string Vocab_77 {
            get {
                return ResourceManager.GetString("Vocab_77", resourceCulture);
            }
        }
    }
}
